name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
        cache-dependency-path: |
          go.sum

    - name: mod download
      run: go mod download

    - name: install go-junit-report
      run: "go install github.com/jstemmer/go-junit-report"

    - name: vet
      run: go vet

    - name: generate
      run: go generate ./...

    - name: Run tests
      env:
        IRDATA_EMAIL: ${{ secrets.IRDATA_EMAIL }}
        IRDATA_PASSWORD: ${{ secrets.IRDATA_PASSWORD }}
      run: go test -v ./... | tee test-output.log

    - name: Convert to JUnit
      run: cat test-output.log | go-junit-report > report.xml
      if: always()

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: |
          report.xml
      if: always()
