name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
        cache-dependency-path: |
          go.sum

    - name: mod download
      run: go mod download

    - name: install go-junit-report
      run: "go install github.com/jstemmer/go-junit-report"

    - name: vet
      run: go vet

    - name: generate
      id: generate
      run: go generate ./...

    - name: Run tests
      id: tests
      continue-on-error: true
      env:
        IRDATA_EMAIL: ${{ secrets.IRDATA_EMAIL }}
        IRDATA_PASSWORD: ${{ secrets.IRDATA_PASSWORD }}
      run: |
        go test -v ./... 2>&1 | tee test-output.log

    - name: Generate Report
      id: convert-to-junit
      continue-on-error: true
      run: cat test-output.log | go-junit-report -set-exit-code > report.xml
      if: steps.generate.outcome == 'success'

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: |
          report.xml
      if: steps.generate.outcome == 'success'

    - name: Test Reports
      uses: xportation/junit-coverage-report@main
      with:
        junit-path: ./report.xml
      if: steps.generate.outcome == 'success'

    - name: Check for test failures
      if: steps.convert-to-junit.outcome == 'failure'
      run: exit 1
